INSERT INTO hymns (h_id, h_title, special_topic, position)
VALUES
	(2, 'El Espíritu de Dios', NULL, 1),
    (3, 'Ya regocijemos', NULL, 1),
    (4, 'Bandera de Sión', NULL, 1),
	(5, 'Oh Dios de Israel', NULL, 1),
	(6, 'Israel, Jesús os llama', NULL, 1),
    (10, 'Te damos, Señor, nuestras gracias', NULL, 1),
	(11, 'Dios manda a profetas', NULL, 1),
	(14, 'La oración del Profeta', NULL, 1),
	(15, 'Loor al Profeta', NULL, 1),
	(16, 'Un pobre forastero', 'Missinary Work', NULL),
	(17, '¡Oh, está todo bien!', NULL, 1),
	(18, 'Oh Sión, santuario de libertad', NULL, 1),
	(19, 'Por Tus dones loor cantamos', NULL, 1),
	(24, 'El alba ya rompe', NULL, 1),
	(26, 'Hijos del Señor, venid', NULL, 1),
	(27, 'Oh Rey de reyes, ven', NULL, 1),
	(28, 'Himno de batalla de la República', NULL, NULL),
	(29, 'Ven, oh día prometido', NULL, 1),
    (30, 'A Cristo Rey Jesús', NULL, NULL),
	(31, 'Oh, creaciones del Señor', NULL, 1),
	(34, 'Oh, Santo Dios, omnipotente ser', NULL, 1),
	(36, 'Padre bendito, venimos a Ti', NULL, 1),
	(38, 'Santos, avanzad', NULL, 1),
	(40, 'Qué firmes cimientos', NULL, 1),
	(41, '¡Grande eres Tú!', NULL, NULL),
	(42, 'Jesús es mi luz', NULL, 1),
	(47, 'Caros niños, Dios os ama', NULL, 1),
    (48, 'Divina Luz', NULL, 1),
	(49, 'Señor, te necesito', NULL, 1),
	(50, 'Más cerca,Dios, de ti', NULL, 1),
	(52, 'Guíame a Ti', NULL, 1),
	(54, 'Paz, cálmense', NULL, 1),
	(55, 'Dios da valor', NULL, 1),
	(56, 'Jehová mi Pastor es', NULL, 1),
	(57, 'El amor del Salvador', NULL, 1),
	(58, 'Roca de eternidad', NULL, 1),
	(60, 'Venid a Cristo', NULL, 1),
	(61, 'Venid a Mí', NULL, 1),
	(66, 'Cuán dulce la ley de Dios', NULL, 1),
    (68	, 'La fe', NULL, NULL),
    (69	, '¿Dónde hallo el solaz?', NULL, NULL),
    (70, 'Sé humilde', NULL, NULL),
    (71, 'Más santidad dame', NULL, NULL),
    (72, 'Creo en Cristo', NULL, NULL),
    (73, 'Yo sé que vive mi Señor', NULL, NULL),
    (74, 'Vive mi Señor', NULL, 1),
    (76, 'Tan sólo con pensar en Ti', NULL, 1),
    (77, 'Deja que el Espíritu te enseñe', NULL, 1),
    (78, 'Oh dulce, grata oración', NULL, 1),
	(80, 'Secreta oración', NULL, 1),
	(81, '¿Pensaste orar?', NULL, 1),
	(83, 'Entonad sagrado son', NULL, 1),
	(85, 'El día santo del Señor', NULL, 1),
	(87, 'Cual rocío, que destila', NULL, 1),
    (88, 'Placentero nos es trabajar', 'Closing', 4),
	(89, 'Para siempre Dios esté con Vos', 'Closing', 4),
	(90, 'Padre, antes de partir', 'Closing', 4),
	(91, 'Al partir cantemos', 'Closing', 4),
	(92, 'Hemos sentido Tu amor', 'Closing', 4),
	(93, 'A Ti, Señor', 'Closing', 4),
	(98, 'Conmigo quédate, Señor', 'Closing', 4),
	(99, 'Acompáñame', 'Closing', 4),
	(100, 'Dios, bendícenos', 'Closing', 4),
	(101, 'Dios, escúchanos orar', NULL, 2),
	(102, 'Hoy con humildad te pido', NULL,	2),
	(103, 'La Santa Cena', NULL, 2),
	(104, 'Oh Dios, Eterno Padre', NULL, 2),
	(105, 'Jesús de Nazaret', NULL,	2),
	(106, 'Cuán grato es cantar loor', NULL,	2),
	(107, 'Pedimos Tu Espíritu'	, NULL,	2),
	(108, 'Mansos, reverentes hoy', NULL, 2),
	(109, 'Cantemos todos a Jesús', NULL, 2),
	(110, 'En memoria de Tu muerte', NULL, 2),
	(111, 'En el Calvario, en la cruz', NULL, 2),
	(112, 'El Padre tanto nos amó', NULL, 2),
	(113, 'Ya nos juntamos otra vez', NULL,	2),
	(114, 'Cristo, el Redentor, murió', NULL, 2),
	(115, 'Nos reunimos, Padre, hoy', NULL,	2),
	(116, 'Jesús, en la corte celestial', NULL,	2),
	(117, '¡Murió! El Redentor murió', NULL, 2),
	(118, 'Asombro me da', NULL, 2),
	(119, 'En un lejano cerro fue', NULL, 2),
	(120, 'Tan humilde al nacer', NULL,	2),
	(137, 'Tú me has dado muchas bendiciones, Dios', NULL, NULL),
	(138, 'Señor, yo te seguiré', 'Missinary Work', NULL),
	(146, 'Tengo gozo en mi alma hoy', NULL, NULL),
	(148, 'Si hay gozo en tu corazón', 'Missinary Work', NULL),
	(150, 'Siembra gozo', NULL,	NULL),
	(152, 'No hablemos con enojo', NULL, NULL),
	(154, 'Haz tú lo justo', NULL, NULL),
	(155, 'Haz el bien', NULL, NULL),
	(157, 'Cuenta tus bendiciones', NULL, NULL),
	(158, 'Trabajemos hoy en la obra', NULL, NULL),
	(159, 'Con valor marchemos'	, NULL,	NULL),
	(160, 'Tu casa amamos, Dios', 'Templos', 1),
	(161, 'Llamados a servir', 'Missinary Work', NULL),
	(162, 'Somos los soldados', NULL, NULL),
	(163, '¡Mirad! Reales huestes', NULL, NULL),
	(164, 'Pon tu hombro a la lid', 'Missinary Work', NULL),
	(167, 'A vencer', NULL,	NULL),
	(168, 'Juventud de Israel', NULL, NULL),
	(169, 'Al mundo ve a predicar', 'Missinary Work', NULL),
	(171, ' La luz de la verdad', NULL,	NULL),
	(172, 'Cuando enseñe a Tus hijos', NULL, NULL),
	(175, 'A donde me mandes iré', 'Missinary Work', NULL),
	(177, '¿Qué es la verdad?', NULL, NULL),
	(179, 'La barra de hierro', NULL, NULL),
	(180, 'Al leer las Escrituras', NULL, NULL),
	(181, 'Cuando raya el nuevo dia', NULL,	NULL),
	(183, 'Santos templos de Sión', 'Templos', NULL),
	(184, 'Id, oh santos, a los templos', 'Templos', NULL),
	(187, 'Oh mi Padre'	, NULL,	NULL),
	(193, 'El hogar es como el cielo', 'Family', NULL),
	(194, 'Cuando hay amor', 'Family', NULL),
	(195, 'Las familias pueden ser eternas', 'Family', NULL),
	(196, 'Soy un hijo de Dios', 'Family', NULL),
	(197, 'Siempre obedece los mandamientos', NULL, NULL),
	(198, 'Hazme andar en la luz', NULL, NULL),
	(199, 'Dios vive', NULL, NULL),
	(202, 'En el pueblo de Sión', 'Family', NULL),
	(203, 'Amad a otros', NULL,	NULL),
	(208, 'Brillan rayos de clemencia', NULL,NULL),
	(1001, 'Fuente de mis bendiciones', NULL, NULL),
	(1002, 'Cuando vuelva el Salvador', NULL, NULL),
	(1003, 'Reina paz en mi ser', NULL,	NULL),
	(1004, 'Andaré con Cristo', NULL, NULL),
	(1005, 'Él cuida de las aves', NULL, NULL),
	(1006, 'En tu corazón entona una canción', NULL, NULL),
	(1008, 'Agua viva, pan de vida', NULL,	2),
	(1009, 'Getsemaní', NULL,	2),
	(1010, 'Sublime gracia', NULL,	NULL),
	(1016, 'Mirad las marcas de Jesús', NULL, 2),
	(1019, 'Amar igual que Tú', NULL, NULL),
	(1021, 'Cristo me ama, lo sé', NULL, NULL),
	(1022, 'Con fe en cada paso', NULL,	NULL),
	(1024, 'Tengo fe en Jesús, mi Señor', NULL,	NULL),
	(1025, 'Hoy te doy mi corazón', NULL, NULL),
	(1026, 'Lugares santos', 'Templos', NULL),
	(1027, 'Soy bienvenido a Su hogar', 'Templos', NULL),
	(1028, 'Mi pequeña luz', NULL,	NULL),
	(1031, 'Venid, oíd la voz de Cristo', NULL,	NULL);